Dirty qemu bypass when host matches selected arch

diff --git a/nethunter-fs/stages/stage1 b/nethunter-fs/stages/stage1
--- a/nethunter-fs/stages/stage1
+++ b/nethunter-fs/stages/stage1
@@ -14,22 +14,27 @@ fi
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-## Docker needs binfmt to run arm
-##   Without below commands second-stage and chroot will fail
-##   REF: https://web.archive.org/web/20191108143948/http://neophob.com/2014/10/run-arm-binaries-in-your-docker-container-using-boot2docker/
-if ! mountpoint -q /proc/sys/fs/binfmt_misc; then
-  echo "[+] binfmt_misc not mounted"
-  mount -v binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
-  if [ -e "/.dockerenv" ]; then
-    ls -lh /proc/sys/fs/binfmt_misc/qemu-* >/dev/null || echo "[!] Try installing qemu-user-static on the host"
-  fi
-fi
-
-echo "[+] Setting up binfmts"
-if [ "$suse" = true ]; then
-  qemu-binfmt-conf.sh
+if [ "$( uname -m )" == "$qemu_arch" ]; then
+  echo "[i] Selected arch is the as host: $qemu_arch"
 else
-  update-binfmts --enable "qemu-$qemu_arch"
+  echo "[i] Selected arch ($qemu_arch) is different arch to host $($( uname -m ))"
+  ## Docker needs binfmt to run arm
+  ##   Without below commands second-stage and chroot will fail
+  ##   REF: https://web.archive.org/web/20191108143948/http://neophob.com/2014/10/run-arm-binaries-in-your-docker-container-using-boot2docker/
+  if ! mountpoint -q /proc/sys/fs/binfmt_misc; then
+    echo "[+] binfmt_misc not mounted"
+    mount -v binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
+    if [ -e "/.dockerenv" ]; then
+      ls -lh /proc/sys/fs/binfmt_misc/qemu-* >/dev/null || echo "[!] Try installing qemu-user-static on the host"
+    fi
+  fi
+
+  echo "[+] Setting up binfmts"
+  if [ "$suse" = true ]; then
+    qemu-binfmt-conf.sh
+  else
+    update-binfmts --enable "qemu-$qemu_arch"
+  fi
 fi
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
